apiVersion: v1
kind: Service
  labels: frontend
spec:
  clusterIP: 10.15.253.97
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30545
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer

