apiVersion: v1
kind: Service
spec:
  clusterIP: 10.15.241.107
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    role: slave
    tier: backend
  sessionAffinity: None
  type: ClusterIP