apiVersion: v1
kind: Service
  labels: redis-master
spec:
  clusterIP: 10.15.255.212
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
  sessionAffinity: None
  type: ClusterIP

