apiVersion: extensions/v1beta1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
    spec:
      containers:
      - env:
        - name: redisslave
          value: dns
        image: gcr.io/google_samples/gb-redisslave:v1
        name: slave
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi